services:
 frontend_siscol:
   build:
     context: .
     dockerfile: Dockerfile
   image: frontend-sicopesc
   container_name: frontend-sicopesc
   ports:
     - "3000:3000"
     - "35729:35729"
   volumes:
     - ./:/app
     - /app/node_modules
   environment:
     - CHOKIDAR_USEPOLLING=true
     - WATCHPACK_POLLING=true
     - FAST_REFRESH=true
     - REACT_APP_API_URL=http://localhost:4000
     - WDS_SOCKET_PORT=35729
   stdin_open: true
   tty: true
   restart: unless-stopped
