services:
  db_siscol:
    image: mysql:8
    container_name: mysql-container
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      UPLOAD_LIMIT: 300000000
      #MYSQL_DATABASE: lms_manager
    ports:
      - 8082:80
    depends_on:
      - db_siscol

  backend_siscol:
    image: node:12
    container_name: backend-siscol-container
    volumes:
      - ./:/home/app
    restart: always
    ports:
      - "4000:4000"
    working_dir: /home/app
    command: bash -c "./wait-for-it.sh db_siscol:3306 --timeout=60 --strict -- bash -c 'npm install && npx sequelize db:migrate && npm run dev  '"
    depends_on:
      - db_siscol
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_NAME}
